appVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: 794038217891.dkr.ecr.ap-south-1.amazonaws.com/travelease/payment:latest
          ports:
            - containerPort: 5070
          env:
            - name: MONGO_URI
              value: "${MONGO_URI_BHAVESH}"
            - name: PORT
              value: "5070"
          resources: 
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"