---
appVersion: apps/v1
kind: Deployment
metadata:
  name: travelease-payment
  labels:
  travelease.io/name: travelease-payment
  app.kubernetes.io/instance: travelease-deploy
  app.kubernetes.io/name: travelease-payment
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      travelease.io/name: travelease-payment
  template:
    metadata:
      labels:
        travelease.io/name: travelease-payment  
        app.kubernetes.io/instance: travelease-deploy
        app.kubernetes.io/name: travelease-payment

    spec:
      serviceAccountName: travelease-deploy   
      containers:
        - name: travelease-payment
          image: 794038217891.dkr.ecr.ap-south-1.amazonaws.com/travelease/payment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5070
          env:
            - name: MONGO_URI
              value: "mongodb+srv://Bhavesh:Admin123@cluster0.ig5deah.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
            - name: PORT
              value: "5070"
          