services:
  booking:
    build: ./booking
    ports:
      - "3001:3001" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb+srv://Sujal:Admin123@cluster0.ig5deah.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 
      
  payment:
    build: ./payment
    ports:
      - "5070:5070" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb+srv://Bhavesh:Admin123@cluster0.ig5deah.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 
      
  login:
    build: ./login
    ports:
      - "5050:5050" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb+srv://Kavya:Admin123@cluster0.ig5deah.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0  

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  
    networks:
      - mern_network
    environment:
      LOGIN_API_URL: http://login:5050 
      PAYMENT_API_URL: http://payment:5070 
      BOOKING_API_URL: http://booking:3001
    depends_on:
      - booking
      - payment
      - login 

networks:
  mern_network:
    driver: bridge 

