services:
  booking:
    build: ./booking
    ports:
      - "3001:3001" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb+srv://Sujal:Admin123@cluster0.ig5deah.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 
      PORT: 3001 
      
  payment:
    build: ./payment
    ports:
      - "5070:5070" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb+srv://Bhavesh:Admin123@cluster0.ig5deah.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 
      PORT: PORT
      
  login:
    build: ./login
    ports:
      - "5050:5050" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb+srv://Kavya:Admin123@cluster0.ig5deah.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0  
      PORT: 5050

  frontend:
    build: ./frontend
    ports:
      - "80:80"  
    networks:
      - mern_network
    environment:
      VITE_LOGIN_API_URL: http://login
      VITE_PAYMENT_API_URL: http://payment
      VITE_BOOKING_API_URL: http://booking
      VITE_BOOKING_PORT: 3001
      VITE_PAYMENT_PORT: 5070
      VITE_LOGIN_PORT: 5050
    depends_on:
      - booking
      - payment
      - login 

networks:
  mern_network:
    driver: bridge 

