appVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: 794038217891.dkr.ecr.ap-south-1.amazonaws.com/travelease/login:latest
          ports:
            - containerPort: 5050
          env:
            - name: MONGO_URI
              value: "${MONGO_URI_BHAVESH}"
            - name: PORT
              value: "5050"
            - name: JWT_SECRET
              value: "y2cjouqyr"
          resources: 
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"