---
appVersion: apps/v1
kind: Deployment
metadata:
  name: travelease-frontend
  labels:
  travelease.io/name: travelease-frontend
  app.kubernetes.io/instance: travelease-deploy
  app.kubernetes.io/name: travelease-frontend
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      travelease.io/name: travelease-frontend
  template:
    metadata:
      labels:
        travelease.io/name: travelease-frontend  
        app.kubernetes.io/instance: travelease-deploy
        app.kubernetes.io/name: travelease-frontend

    spec:
      serviceAccountName: travelease-deploy   
      containers:
        - name: travelease-frontend
          image: 794038217891.dkr.ecr.ap-south-1.amazonaws.com/travelease/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: VITE_LOGIN_API_URL
              value: "/api/login"
            - name: VITE_PAYMENT_API_URL
              value: "/api/payment"
            - name: VITE_BOOKING_API_URL
              value: "/api/booking"           
          