apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: example.com
      http:
        paths:
          # MOST SPECIFIC PATHS FIRST
          - path: "/api/login"
            pathType: Prefix
            backend:
              service:
                name: travelease-login
                port:
                  number: 5050

          - path: "/api/payment"
            pathType: Prefix
            backend:
              service:
                name: travelease-payment
                port:
                  number: 5070

          - path: "/api/booking"
            pathType: Prefix
            backend:
              service:
                name: travelease-booking
                port:
                  number: 3001

          # LEAST SPECIFIC PATH LAST
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: travelease-frontend
                port:
                  number: 80
