---
apiVersion: v1
kind: Service
metadata:
  name: travelease-frontend
  labels:
    travelease.io/name: travelease-frontend
    app.kubernetes.io/instance: travelease-deploy
    app.kubernetes.io/name: travelease-frontend
spec: 
  type: ClusterIP
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 80 
  selector:
    travelease.io/name: travelease-frontend  