appVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: 794038217891.dkr.ecr.ap-south-1.amazonaws.com/travelease/booking:latest
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              value: "${MONGO_URI_BHAVESH}"
            - name: PORT
              value: "3001"
          resources: 
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"